package com.kayleemclaren.payment.model

import jakarta.persistence.*
import java.math.BigDecimal
import java.time.LocalDateTime

/**
 * Payment Entity - Database Model
 *
 * Key Concepts:
 * - @Entity: Marks this class as a JPA entity (maps to database table)
 * - @Table: Specifies the table name in the database
 * - data class: Kotlin feature that auto-generates equals(), hashCode(), toString(), copy()
 * - JPA Annotations: Define how fields map to database columns
 *
 * Field Mutability Rules:
 * - val = immutable (cannot be reassigned) - use for data that shouldn't change
 * - var = mutable (can be reassigned) - use for data that updates
 *
 * Nullable vs Non-Nullable:
 * - Type (e.g., String) = non-nullable, cannot be null
 * - Type? (e.g., String?) = nullable, can be null
 * - nullable = false in @Column = database constraint (NOT NULL in SQL)
 */
@Entity
@Table(name = "payments")
data class Payment(

    // Primary Key - Auto-generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Auto-increment
    val id: Long? = null,  // Nullable because DB generates it, immutable because IDs never change

    // Payment Amount - CRITICAL: Always use BigDecimal for money!
    // Never use Double or Float for currency (precision errors)
    @Column(nullable = false)  // NOT NULL constraint in database
    val amount: BigDecimal,  // Immutable - payment amounts shouldn't change after creation

    // Currency Code
    @Column(nullable = false, length = 3)  // VARCHAR(3) NOT NULL
    val currency: String,  // Immutable - e.g., "USD", "EUR", "GBP"

    // Sender Information
    @Column(nullable = false)
    val senderId: String,  // Immutable - who sent the payment

    // Recipient Information
    @Column(nullable = false)
    val recipientId: String,  // Immutable - who receives the payment

    // Payment Status - Tracks lifecycle (PENDING → PROCESSING → COMPLETED/FAILED)
    @Enumerated(EnumType.STRING)  // Store enum as string in DB, not ordinal (safer)
    @Column(nullable = false)
    var status: PaymentStatus = PaymentStatus.PENDING,  // Mutable - status changes as payment processes

    // Optional Description
    @Column(length = 500)  // VARCHAR(500), nullable = true (default)
    var description: String? = null,  // Nullable type (?) - description is optional

    // Audit Timestamps
    @Column(nullable = false, updatable = false)  // Set once, never updated
    val createdAt: LocalDateTime = LocalDateTime.now(),  // Immutable - creation timestamp

    @Column(nullable = false)  // Can be updated
    var updatedAt: LocalDateTime = LocalDateTime.now()  // Mutable - tracks last modification
)